# Modeling

In [3]:
from datetime import datetime
start_time = datetime.now()

# Libraries to load
!pip install lightgbm

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
import lightgbm as lgb
import numpy as np
%matplotlib inline

print('LOAD DURATION: ', datetime.now() - start_time) # load time about 30 seconds

Requirement already satisfied: lightgbm in /opt/anaconda3/lib/python3.8/site-packages (3.3.2)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.8/site-packages (from lightgbm) (1.5.2)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.8/site-packages (from lightgbm) (1.19.2)
Requirement already satisfied: scikit-learn!=0.22.0 in /opt/anaconda3/lib/python3.8/site-packages (from lightgbm) (0.23.2)
Requirement already satisfied: wheel in /opt/anaconda3/lib/python3.8/site-packages (from lightgbm) (0.35.1)
Requirement already satisfied: joblib>=0.11 in /opt/anaconda3/lib/python3.8/site-packages (from scikit-learn!=0.22.0->lightgbm) (0.17.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/anaconda3/lib/python3.8/site-packages (from scikit-learn!=0.22.0->lightgbm) (2.1.0)
LOAD DURATION:  0:00:10.950494

In [5]:
vars=pd.read_csv('VarsFS.csv')
vars.head(5)

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
0,"(3,)",[0.35173254 0.35678217],0.354257,fulladdress_count_30,0.010863,0.002525,0.002525
1,"(3, 83)",[0.50356956 0.53543444],0.519502,ssn_dob_count_30,0.068552,0.015932,0.015932
2,"(3, 10, 83)",[0.50705206 0.53543444],0.521243,fulladdress_unique_count_for_dob_homephone_60,0.061060,0.014191,0.014191
3,"(3, 8, 10, 83)",[0.50740031 0.53978757],0.523594,address_count_0_by_30,0.069676,0.016194,0.016194
4,"(3, 8, 10, 48, 83)",[0.50670381 0.54152882],0.524116,fulladdress_unique_count_for_ssn_lastname_7,0.074920,0.017413,0.017413

In [77]:
var_1= pd.read_csv('vars.csv')
var_1.shape

(1000000, 1021)

In [4]:
%%time
var_1.head(5)

CPU times: user 780 Âµs, sys: 3.37 ms, total: 4.15 ms
Wall time: 27 ms

,Unnamed: 0,record,date,ssn,firstname,lastname,address,zip5,dob,homephone,...,ssn_name_dob_unique_count_for_ssn_name_7,ssn_name_dob_unique_count_for_ssn_name_14,ssn_name_dob_unique_count_for_ssn_name_30,ssn_name_dob_unique_count_for_ssn_name_60,ssn_name_dob_unique_count_for_ssn_fulladdress_1,ssn_name_dob_unique_count_for_ssn_fulladdress_3,ssn_name_dob_unique_count_for_ssn_fulladdress_7,ssn_name_dob_unique_count_for_ssn_fulladdress_14,ssn_name_dob_unique_count_for_ssn_fulladdress_30,ssn_name_dob_unique_count_for_ssn_fulladdress_60
0,0,1,2016-01-01,379070012,XRRAMMTR,SMJETJMJ,6861 EUTST PL,2765,000000-1,1797504115,...,1,1,1,1,1,1,1,1,1,1
1,1,2,2016-01-01,387482503,MAMSTUJR,RTTEMRRR,7280 URASA PL,57169,19340615,4164239415,...,1,1,1,1,1,1,1,1,1,1
2,2,3,2016-01-01,200332444,SZMMUJEZS,EUSEZRAE,5581 RSREX LN,56721,000000-3,0216537580,...,1,1,1,1,1,1,1,1,1,1
3,3,4,2016-01-01,747451317,SJJZSXRSZ,ETJXTXXS,1387 UJZXJ RD,35286,19440430,0132144161,...,1,1,1,1,1,1,1,1,1,1
4,4,5,2016-01-01,024065868,SSSXUEJMS,SSUUJXUZ,279 EAASA WY,3173,19980315,6101082272,...,1,1,1,1,1,1,1,1,1,1

In [17]:
var_final_save=pd.DataFrame()
var_final_save

Empty DataFrame
Columns: []
Index: []

In [23]:
list=[]
list.append('record')
for i in vars['feature_names'].to_list():
    list.append(i)
list.append('fraud_label')
list

['record',
 'fulladdress_count_30',
 'ssn_dob_count_30',
 'fulladdress_unique_count_for_dob_homephone_60',
 'address_count_0_by_30',
 'fulladdress_unique_count_for_ssn_lastname_7',
 'fulladdress_unique_count_for_name_dob_30',
 'fulladdress_unique_count_for_name_dob_60',
 'fulladdress_unique_count_for_ssn_name_dob_60',
 'fulladdress_count_0_by_30',
 'fulladdress_unique_count_for_ssn_name_7',
 'fulladdress_unique_count_for_ssn_lastname_14',
 'ssn_firstname_count_30',
 'ssn_count_30',
 'fulladdress_unique_count_for_ssn_30',
 'fulladdress_unique_count_for_ssn_name_dob_7',
 'fulladdress_unique_count_for_name_fulladdress_14',
 'fulladdress_unique_count_for_name_dob_14',
 'fulladdress_unique_count_for_ssn_name_dob_14',
 'fulladdress_unique_count_for_fulladdress_dob_14',
 'fulladdress_unique_count_for_ssn_zip5_30',
 'fulladdress_unique_count_for_dob_homephone_7',
 'fulladdress_unique_count_for_dob_homephone_14',
 'fulladdress_count_14',
 'fulladdress_unique_count_for_fulladdress_dob_7',
 'address_count_30',
 'fulladdress_unique_count_for_name_fulladdress_7',
 'fulladdress_unique_count_for_ssn_60',
 'fulladdress_unique_count_for_ssn_fulladdress_30',
 'fulladdress_unique_count_for_ssn_name_14',
 'fulladdress_unique_count_for_ssn_lastname_60',
 'fraud_label']

In [24]:
for i in list:
    var_final_save[i]= var_1[i]

var_final_save.head(5)

,record,fulladdress_count_30,ssn_dob_count_30,fulladdress_unique_count_for_dob_homephone_60,address_count_0_by_30,fulladdress_unique_count_for_ssn_lastname_7,fulladdress_unique_count_for_name_dob_30,fulladdress_unique_count_for_name_dob_60,fulladdress_unique_count_for_ssn_name_dob_60,fulladdress_count_0_by_30,...,fulladdress_unique_count_for_dob_homephone_14,fulladdress_count_14,fulladdress_unique_count_for_fulladdress_dob_7,address_count_30,fulladdress_unique_count_for_name_fulladdress_7,fulladdress_unique_count_for_ssn_60,fulladdress_unique_count_for_ssn_fulladdress_30,fulladdress_unique_count_for_ssn_name_14,fulladdress_unique_count_for_ssn_lastname_60,fraud_label
0,1,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
1,2,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,1
2,3,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
3,4,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
4,5,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0

In [4]:
var_final_save.to_csv('vars_final_save.csv', index=False)

NameError: name 'var_final_save' is not defined

In [120]:
%%time
vars=pd.read_csv('vars_final_save.csv')
vars.head(5)

CPU times: user 1.77 s, sys: 418 ms, total: 2.19 s
Wall time: 2.46 s

,record,fulladdress_count_30,ssn_dob_count_30,fulladdress_unique_count_for_dob_homephone_60,address_count_0_by_30,fulladdress_unique_count_for_ssn_lastname_7,fulladdress_unique_count_for_name_dob_30,fulladdress_unique_count_for_name_dob_60,fulladdress_unique_count_for_ssn_name_dob_60,fulladdress_count_0_by_30,...,fulladdress_unique_count_for_dob_homephone_14,fulladdress_count_14,fulladdress_unique_count_for_fulladdress_dob_7,address_count_30,fulladdress_unique_count_for_name_fulladdress_7,fulladdress_unique_count_for_ssn_60,fulladdress_unique_count_for_ssn_fulladdress_30,fulladdress_unique_count_for_ssn_name_14,fulladdress_unique_count_for_ssn_lastname_60,fraud_label
0,1,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
1,2,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,1
2,3,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
3,4,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
4,5,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0

In [121]:
# use this to cap variables. For some problems it helps
Clip = 10

In [122]:
vars['fraud_label'].sum()

14393

In [123]:
vars.head(10)

,record,fulladdress_count_30,ssn_dob_count_30,fulladdress_unique_count_for_dob_homephone_60,address_count_0_by_30,fulladdress_unique_count_for_ssn_lastname_7,fulladdress_unique_count_for_name_dob_30,fulladdress_unique_count_for_name_dob_60,fulladdress_unique_count_for_ssn_name_dob_60,fulladdress_count_0_by_30,...,fulladdress_unique_count_for_dob_homephone_14,fulladdress_count_14,fulladdress_unique_count_for_fulladdress_dob_7,address_count_30,fulladdress_unique_count_for_name_fulladdress_7,fulladdress_unique_count_for_ssn_60,fulladdress_unique_count_for_ssn_fulladdress_30,fulladdress_unique_count_for_ssn_name_14,fulladdress_unique_count_for_ssn_lastname_60,fraud_label
0,1,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
1,2,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,1
2,3,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
3,4,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
4,5,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
5,6,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
6,7,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
7,8,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
8,9,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
9,10,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0

In [124]:
vars.shape

(1000000, 32)

In [125]:
vars.describe()

,record,fulladdress_count_30,ssn_dob_count_30,fulladdress_unique_count_for_dob_homephone_60,address_count_0_by_30,fulladdress_unique_count_for_ssn_lastname_7,fulladdress_unique_count_for_name_dob_30,fulladdress_unique_count_for_name_dob_60,fulladdress_unique_count_for_ssn_name_dob_60,fulladdress_count_0_by_30,...,fulladdress_unique_count_for_dob_homephone_14,fulladdress_count_14,fulladdress_unique_count_for_fulladdress_dob_7,address_count_30,fulladdress_unique_count_for_name_fulladdress_7,fulladdress_unique_count_for_ssn_60,fulladdress_unique_count_for_ssn_fulladdress_30,fulladdress_unique_count_for_ssn_name_14,fulladdress_unique_count_for_ssn_lastname_60,fraud_label
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,500000.500000,1.064624,1.046097,1.044485,29.359901,1.031739,1.038716,1.043294,1.043802,29.491030,...,1.035599,1.047969,1.032313,1.078171,1.031652,1.038559,1.036240,1.034144,1.038636,0.014393
std,288675.278933,0.633831,0.496315,0.617953,3.201461,0.574921,0.609942,0.617028,0.618063,2.831175,...,0.596144,0.606858,0.575101,0.664121,0.574846,0.613686,0.608032,0.595013,0.613757,0.119104
min,1.000000,1.000000,1.000000,1.000000,1.304348,1.000000,1.000000,1.000000,1.000000,1.304348,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,250000.750000,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1.000000,30.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
50%,500000.500000,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1.000000,30.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
75%,750000.250000,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1.000000,30.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,1000000.000000,30.000000,34.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,...,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,1.000000

In [126]:
record_save = vars['record']
Y_save = pd.DataFrame(vars.loc[:,'fraud_label'])
Y_save.head()

   fraud_label
0            0
1            1
2            0
3            0
4            0

## Scale and truncate field values

In [127]:
X_no_scaling = vars.drop(columns = ['record','fraud_label'])
X_no_scaling.describe()

,fulladdress_count_30,ssn_dob_count_30,fulladdress_unique_count_for_dob_homephone_60,address_count_0_by_30,fulladdress_unique_count_for_ssn_lastname_7,fulladdress_unique_count_for_name_dob_30,fulladdress_unique_count_for_name_dob_60,fulladdress_unique_count_for_ssn_name_dob_60,fulladdress_count_0_by_30,fulladdress_unique_count_for_ssn_name_7,...,fulladdress_unique_count_for_dob_homephone_7,fulladdress_unique_count_for_dob_homephone_14,fulladdress_count_14,fulladdress_unique_count_for_fulladdress_dob_7,address_count_30,fulladdress_unique_count_for_name_fulladdress_7,fulladdress_unique_count_for_ssn_60,fulladdress_unique_count_for_ssn_fulladdress_30,fulladdress_unique_count_for_ssn_name_14,fulladdress_unique_count_for_ssn_lastname_60
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,1.064624,1.046097,1.044485,29.359901,1.031739,1.038716,1.043294,1.043802,29.491030,1.031745,...,1.032526,1.035599,1.047969,1.032313,1.078171,1.031652,1.038559,1.036240,1.034144,1.038636
std,0.633831,0.496315,0.617953,3.201461,0.574921,0.609942,0.617028,0.618063,2.831175,0.574926,...,0.575568,0.596144,0.606858,0.575101,0.664121,0.574846,0.613686,0.608032,0.595013,0.613757
min,1.000000,1.000000,1.000000,1.304348,1.000000,1.000000,1.000000,1.000000,1.304348,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1.000000,30.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1.000000,30.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1.000000,30.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,30.000000,34.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,...,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000

In [128]:
X = (X_no_scaling - X_no_scaling.mean()) / X_no_scaling.std()

In [129]:
# push in any outlier values
cols = X.columns
X.loc[:,cols] = X[cols].clip(upper=Clip)
X.loc[:,cols] = X[cols].clip(lower=-1*Clip)
# X = (X_no_scaling - X_no_scaling.mean()) / X_no_scaling.std()
X.describe()

,fulladdress_count_30,ssn_dob_count_30,fulladdress_unique_count_for_dob_homephone_60,address_count_0_by_30,fulladdress_unique_count_for_ssn_lastname_7,fulladdress_unique_count_for_name_dob_30,fulladdress_unique_count_for_name_dob_60,fulladdress_unique_count_for_ssn_name_dob_60,fulladdress_count_0_by_30,fulladdress_unique_count_for_ssn_name_7,...,fulladdress_unique_count_for_dob_homephone_7,fulladdress_unique_count_for_dob_homephone_14,fulladdress_count_14,fulladdress_unique_count_for_fulladdress_dob_7,address_count_30,fulladdress_unique_count_for_name_fulladdress_7,fulladdress_unique_count_for_ssn_60,fulladdress_unique_count_for_ssn_fulladdress_30,fulladdress_unique_count_for_ssn_name_14,fulladdress_unique_count_for_ssn_lastname_60
count,1000000.000000,1000000.000000,1000000.000000,1.000000e+06,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1.000000e+06,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,-0.018176,-0.017649,-0.019380,7.459644e-14,-0.019766,-0.019734,-0.019447,-0.019413,-8.709182e-14,-0.019766,...,-0.019715,-0.019706,-0.018944,-0.019733,-0.016786,-0.019772,-0.019736,-0.019877,-0.019798,-0.019730
std,0.631721,0.571302,0.591268,1.000000e+00,0.550960,0.577521,0.588890,0.590648,1.000000e+00,0.550975,...,0.552953,0.569360,0.597081,0.552516,0.678129,0.550731,0.579228,0.572323,0.566048,0.579416
min,-0.101958,-0.092879,-0.071988,-8.763360e+00,-0.055206,-0.063475,-0.070165,-0.070870,-9.955826e+00,-0.055216,...,-0.056511,-0.059715,-0.079045,-0.056187,-0.117706,-0.055062,-0.062832,-0.059602,-0.057384,-0.062950
25%,-0.101958,-0.092879,-0.071988,1.999398e-01,-0.055206,-0.063475,-0.070165,-0.070870,1.797736e-01,-0.055216,...,-0.056511,-0.059715,-0.079045,-0.056187,-0.117706,-0.055062,-0.062832,-0.059602,-0.057384,-0.062950
50%,-0.101958,-0.092879,-0.071988,1.999398e-01,-0.055206,-0.063475,-0.070165,-0.070870,1.797736e-01,-0.055216,...,-0.056511,-0.059715,-0.079045,-0.056187,-0.117706,-0.055062,-0.062832,-0.059602,-0.057384,-0.062950
75%,-0.101958,-0.092879,-0.071988,1.999398e-01,-0.055206,-0.063475,-0.070165,-0.070870,1.797736e-01,-0.055216,...,-0.056511,-0.059715,-0.079045,-0.056187,-0.117706,-0.055062,-0.062832,-0.059602,-0.057384,-0.062950
max,10.000000,10.000000,10.000000,1.999398e-01,10.000000,10.000000,10.000000,10.000000,1.797736e-01,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [130]:
# separate data into modeling (traintest) and out of time
X_trntst = X[0:833507]
Y_trntst = Y_save[0:833507]
X_oot = X[833507:]
Y_oot = Y_save[833507:]

In [131]:
niter = 0
nitermax = 3
FDR3 = pd.DataFrame(np.zeros((nitermax,3)), columns=('trn', 'tst', 'oot'))
X_oot_orig = X_oot.copy()
pd.options.mode.chained_assignment = None  # default='warn'

In [ ]:
penalty='l2',C=1, solver='lbfgs', l1_ratio=None

In [ ]:
LogisticRegression()
penalty='l2', *, dual=False, tol=0.0001, C=1, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='lbfgs', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None) -> None

In [64]:
%%time
# Logistic regression with 30 variables

for niter in range(nitermax):    
    X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

    model = LogisticRegression(penalty='l2',C=1, solver='sag', l1_ratio=0.6)
 
    X_oot = X_oot_orig.copy()
    X_trn_save = X_trn.copy()
    Y_trn_save = Y_trn.copy()

    model.fit(X_trn, Y_trn.values.ravel())   

    predictions = model.predict_proba(X_trn_save)[:,1]
    X_trn['predicted'] = predictions
    X_trn['fraud_label'] = Y_trn_save['fraud_label']
    topRows = int(round(X_trn.shape[0]*0.03))
    temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'fraud_label'])

    predictions = model.predict_proba(X_tst)[:,1]
    X_tst['predicted']=predictions
    X_tst['fraud_label'] = Y_tst['fraud_label']
    topRows = int(round(X_tst.shape[0]*0.03))
    temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'fraud_label'])

    predictions = model.predict_proba(X_oot)[:,1]
    X_oot['predicted']=predictions
    X_oot['fraud_label'] = Y_oot['fraud_label']
    topRows = int(round(X_oot.shape[0]*0.03))
    temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'fraud_label'])
    print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
    
print(FDR3.mean())
print(FDR3)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:1315: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn("l1_ratio parameter is only used when penalty is "
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "

0 0.49172772394233044 0.48857545839210154 0.47694886839899414

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:1315: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn("l1_ratio parameter is only used when penalty is "
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "

1 0.4897934821535156 0.49421487603305786 0.4765297569153395

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:1315: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn("l1_ratio parameter is only used when penalty is "
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "

2 0.4889021479713604 0.4948993658671078 0.47694886839899414
trn    0.490141
tst    0.492563
oot    0.476809
dtype: float64
        trn       tst       oot
0  0.491728  0.488575  0.476949
1  0.489793  0.494215  0.476530
2  0.488902  0.494899  0.476949
CPU times: user 2min 10s, sys: 4.89 s, total: 2min 15s
Wall time: 2min 47s

In [93]:
# logistic regression with 25 variables
vars_2 = pd.read_csv('vars_final_save.csv')
vars_2.head(5)

,record,fulladdress_count_30,ssn_dob_count_30,fulladdress_unique_count_for_dob_homephone_60,address_count_0_by_30,fulladdress_unique_count_for_ssn_lastname_7,fulladdress_unique_count_for_name_dob_30,fulladdress_unique_count_for_name_dob_60,fulladdress_unique_count_for_ssn_name_dob_60,fulladdress_count_0_by_30,...,fulladdress_unique_count_for_dob_homephone_14,fulladdress_count_14,fulladdress_unique_count_for_fulladdress_dob_7,address_count_30,fulladdress_unique_count_for_name_fulladdress_7,fulladdress_unique_count_for_ssn_60,fulladdress_unique_count_for_ssn_fulladdress_30,fulladdress_unique_count_for_ssn_name_14,fulladdress_unique_count_for_ssn_lastname_60,fraud_label
0,1,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
1,2,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,1
2,3,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
3,4,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
4,5,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0

In [94]:
vars_2.columns

Index(['record', 'fulladdress_count_30', 'ssn_dob_count_30',
       'fulladdress_unique_count_for_dob_homephone_60',
       'address_count_0_by_30', 'fulladdress_unique_count_for_ssn_lastname_7',
       'fulladdress_unique_count_for_name_dob_30',
       'fulladdress_unique_count_for_name_dob_60',
       'fulladdress_unique_count_for_ssn_name_dob_60',
       'fulladdress_count_0_by_30', 'fulladdress_unique_count_for_ssn_name_7',
       'fulladdress_unique_count_for_ssn_lastname_14',
       'ssn_firstname_count_30', 'ssn_count_30',
       'fulladdress_unique_count_for_ssn_30',
       'fulladdress_unique_count_for_ssn_name_dob_7',
       'fulladdress_unique_count_for_name_fulladdress_14',
       'fulladdress_unique_count_for_name_dob_14',
       'fulladdress_unique_count_for_ssn_name_dob_14',
       'fulladdress_unique_count_for_fulladdress_dob_14',
       'fulladdress_unique_count_for_ssn_zip5_30',
       'fulladdress_unique_count_for_dob_homephone_7',
       'fulladdress_unique_count_for_dob_homephone_14', 'fulladdress_count_14',
       'fulladdress_unique_count_for_fulladdress_dob_7', 'address_count_30',
       'fulladdress_unique_count_for_name_fulladdress_7',
       'fulladdress_unique_count_for_ssn_60',
       'fulladdress_unique_count_for_ssn_fulladdress_30',
       'fulladdress_unique_count_for_ssn_name_14',
       'fulladdress_unique_count_for_ssn_lastname_60', 'fraud_label'],
      dtype='object')

In [95]:
list =['record', 'fulladdress_count_30', 'ssn_dob_count_30',
       'fulladdress_unique_count_for_dob_homephone_60',
       'address_count_0_by_30', 'fulladdress_unique_count_for_ssn_lastname_7',
       'fulladdress_unique_count_for_name_dob_30',
       'fulladdress_unique_count_for_name_dob_60',
       'fulladdress_unique_count_for_ssn_name_dob_60',
       'fulladdress_count_0_by_30', 'fulladdress_unique_count_for_ssn_name_7',
       'fulladdress_unique_count_for_ssn_lastname_14',
       'ssn_firstname_count_30', 'ssn_count_30',
       'fulladdress_unique_count_for_ssn_30',
       'fulladdress_unique_count_for_ssn_name_dob_7',
       'fulladdress_unique_count_for_name_fulladdress_14',
       'fulladdress_unique_count_for_name_dob_14',
       'fulladdress_unique_count_for_ssn_name_dob_14',
       'fulladdress_unique_count_for_fulladdress_dob_14',
       'fulladdress_unique_count_for_ssn_zip5_30',
       'fulladdress_unique_count_for_dob_homephone_7',
       'fulladdress_unique_count_for_dob_homephone_14', 'fulladdress_count_14',
       'fulladdress_unique_count_for_fulladdress_dob_7', 'address_count_30', 'fraud_label']

list

['record',
 'fulladdress_count_30',
 'ssn_dob_count_30',
 'fulladdress_unique_count_for_dob_homephone_60',
 'address_count_0_by_30',
 'fulladdress_unique_count_for_ssn_lastname_7',
 'fulladdress_unique_count_for_name_dob_30',
 'fulladdress_unique_count_for_name_dob_60',
 'fulladdress_unique_count_for_ssn_name_dob_60',
 'fulladdress_count_0_by_30',
 'fulladdress_unique_count_for_ssn_name_7',
 'fulladdress_unique_count_for_ssn_lastname_14',
 'ssn_firstname_count_30',
 'ssn_count_30',
 'fulladdress_unique_count_for_ssn_30',
 'fulladdress_unique_count_for_ssn_name_dob_7',
 'fulladdress_unique_count_for_name_fulladdress_14',
 'fulladdress_unique_count_for_name_dob_14',
 'fulladdress_unique_count_for_ssn_name_dob_14',
 'fulladdress_unique_count_for_fulladdress_dob_14',
 'fulladdress_unique_count_for_ssn_zip5_30',
 'fulladdress_unique_count_for_dob_homephone_7',
 'fulladdress_unique_count_for_dob_homephone_14',
 'fulladdress_count_14',
 'fulladdress_unique_count_for_fulladdress_dob_7',
 'address_count_30',
 'fraud_label']

In [96]:
var_final_save_2=pd.DataFrame()
for i in list:
    var_final_save_2[i] = var_1[i]

var_final_save_2.head(5)

,record,fulladdress_count_30,ssn_dob_count_30,fulladdress_unique_count_for_dob_homephone_60,address_count_0_by_30,fulladdress_unique_count_for_ssn_lastname_7,fulladdress_unique_count_for_name_dob_30,fulladdress_unique_count_for_name_dob_60,fulladdress_unique_count_for_ssn_name_dob_60,fulladdress_count_0_by_30,...,fulladdress_unique_count_for_name_dob_14,fulladdress_unique_count_for_ssn_name_dob_14,fulladdress_unique_count_for_fulladdress_dob_14,fulladdress_unique_count_for_ssn_zip5_30,fulladdress_unique_count_for_dob_homephone_7,fulladdress_unique_count_for_dob_homephone_14,fulladdress_count_14,fulladdress_unique_count_for_fulladdress_dob_7,address_count_30,fraud_label
0,1,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
1,2,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,1
2,3,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
3,4,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0
4,5,1,1,1,30.0,1,1,1,1,30.0,...,1,1,1,1,1,1,1,1,1,0

In [97]:
var_final_save_2.to_csv('vars_final_save_2.csv')

In [98]:
vars_2=pd.read_csv('vars_final_save_2.csv')
vars_2.head(5)

,Unnamed: 0,record,fulladdress_count_30,ssn_dob_count_30,fulladdress_unique_count_for_dob_homephone_60,address_count_0_by_30,fulladdress_unique_count_for_ssn_lastname_7,fulladdress_unique_count_for_name_dob_30,fulladdress_unique_count_for_name_dob_60,fulladdress_unique_count_for_ssn_name_dob_60,...,fulladdress_unique_count_for_name_dob_14,fulladdress_unique_count_for_ssn_name_dob_14,fulladdress_unique_count_for_fulladdress_dob_14,fulladdress_unique_count_for_ssn_zip5_30,fulladdress_unique_count_for_dob_homephone_7,fulladdress_unique_count_for_dob_homephone_14,fulladdress_count_14,fulladdress_unique_count_for_fulladdress_dob_7,address_count_30,fraud_label
0,0,1,1,1,1,30.0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
1,1,2,1,1,1,30.0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,2,3,1,1,1,30.0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
3,3,4,1,1,1,30.0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
4,4,5,1,1,1,30.0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0

In [99]:
record_save = vars_2['record']
Y_save = pd.DataFrame(vars_2.loc[:,'fraud_label'])
Y_save.head()

   fraud_label
0            0
1            1
2            0
3            0
4            0

In [100]:
X_no_scaling = vars_2.drop(columns = ['record','fraud_label'])
X_no_scaling.describe()

,Unnamed: 0,fulladdress_count_30,ssn_dob_count_30,fulladdress_unique_count_for_dob_homephone_60,address_count_0_by_30,fulladdress_unique_count_for_ssn_lastname_7,fulladdress_unique_count_for_name_dob_30,fulladdress_unique_count_for_name_dob_60,fulladdress_unique_count_for_ssn_name_dob_60,fulladdress_count_0_by_30,...,fulladdress_unique_count_for_name_fulladdress_14,fulladdress_unique_count_for_name_dob_14,fulladdress_unique_count_for_ssn_name_dob_14,fulladdress_unique_count_for_fulladdress_dob_14,fulladdress_unique_count_for_ssn_zip5_30,fulladdress_unique_count_for_dob_homephone_7,fulladdress_unique_count_for_dob_homephone_14,fulladdress_count_14,fulladdress_unique_count_for_fulladdress_dob_7,address_count_30
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,499999.500000,1.064624,1.046097,1.044485,29.359901,1.031739,1.038716,1.043294,1.043802,29.491030,...,1.033946,1.035291,1.035421,1.035214,1.036240,1.032526,1.035599,1.047969,1.032313,1.078171
std,288675.278933,0.633831,0.496315,0.617953,3.201461,0.574921,0.609942,0.617028,0.618063,2.831175,...,0.594816,0.595903,0.596039,0.595559,0.608032,0.575568,0.596144,0.606858,0.575101,0.664121
min,0.000000,1.000000,1.000000,1.000000,1.304348,1.000000,1.000000,1.000000,1.000000,1.304348,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,249999.750000,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1.000000,30.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,499999.500000,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1.000000,30.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,749999.250000,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1.000000,30.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,999999.000000,30.000000,34.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,...,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000

In [101]:
X = (X_no_scaling - X_no_scaling.mean()) / X_no_scaling.std()

In [102]:
# push in any outlier values
cols = X.columns
X.loc[:,cols] = X[cols].clip(upper=Clip)
X.loc[:,cols] = X[cols].clip(lower=-1*Clip)
# X = (X_no_scaling - X_no_scaling.mean()) / X_no_scaling.std()
X.describe()

,Unnamed: 0,fulladdress_count_30,ssn_dob_count_30,fulladdress_unique_count_for_dob_homephone_60,address_count_0_by_30,fulladdress_unique_count_for_ssn_lastname_7,fulladdress_unique_count_for_name_dob_30,fulladdress_unique_count_for_name_dob_60,fulladdress_unique_count_for_ssn_name_dob_60,fulladdress_count_0_by_30,...,fulladdress_unique_count_for_name_fulladdress_14,fulladdress_unique_count_for_name_dob_14,fulladdress_unique_count_for_ssn_name_dob_14,fulladdress_unique_count_for_fulladdress_dob_14,fulladdress_unique_count_for_ssn_zip5_30,fulladdress_unique_count_for_dob_homephone_7,fulladdress_unique_count_for_dob_homephone_14,fulladdress_count_14,fulladdress_unique_count_for_fulladdress_dob_7,address_count_30
count,1.000000e+06,1000000.000000,1000000.000000,1000000.000000,1.000000e+06,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1.000000e+06,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,-5.830825e-17,-0.018176,-0.017649,-0.019380,7.459644e-14,-0.019766,-0.019734,-0.019447,-0.019413,-8.709182e-14,...,-0.019813,-0.019725,-0.019714,-0.019735,-0.019877,-0.019715,-0.019706,-0.018944,-0.019733,-0.016786
std,1.000000e+00,0.631721,0.571302,0.591268,1.000000e+00,0.550960,0.577521,0.588890,0.590648,1.000000e+00,...,0.565475,0.568656,0.569048,0.568562,0.572323,0.552953,0.569360,0.597081,0.552516,0.678129
min,-1.732048e+00,-0.101958,-0.092879,-0.071988,-8.763360e+00,-0.055206,-0.063475,-0.070165,-0.070870,-9.955826e+00,...,-0.057070,-0.059223,-0.059427,-0.059128,-0.059602,-0.056511,-0.059715,-0.079045,-0.056187,-0.117706
25%,-8.660241e-01,-0.101958,-0.092879,-0.071988,1.999398e-01,-0.055206,-0.063475,-0.070165,-0.070870,1.797736e-01,...,-0.057070,-0.059223,-0.059427,-0.059128,-0.059602,-0.056511,-0.059715,-0.079045,-0.056187,-0.117706
50%,0.000000e+00,-0.101958,-0.092879,-0.071988,1.999398e-01,-0.055206,-0.063475,-0.070165,-0.070870,1.797736e-01,...,-0.057070,-0.059223,-0.059427,-0.059128,-0.059602,-0.056511,-0.059715,-0.079045,-0.056187,-0.117706
75%,8.660241e-01,-0.101958,-0.092879,-0.071988,1.999398e-01,-0.055206,-0.063475,-0.070165,-0.070870,1.797736e-01,...,-0.057070,-0.059223,-0.059427,-0.059128,-0.059602,-0.056511,-0.059715,-0.079045,-0.056187,-0.117706
max,1.732048e+00,10.000000,10.000000,10.000000,1.999398e-01,10.000000,10.000000,10.000000,10.000000,1.797736e-01,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [103]:
# separate data into modeling (traintest) and out of time
X_trntst = X[0:833507]
Y_trntst = Y_save[0:833507]
X_oot = X[833507:]
Y_oot = Y_save[833507:]

In [104]:
niter = 0
nitermax = 3
FDR3 = pd.DataFrame(np.zeros((nitermax,3)), columns=('trn', 'tst', 'oot'))
X_oot_orig = X_oot.copy()
pd.options.mode.chained_assignment = None  # default='warn'

In [119]:
# Logistic regression with 25 variables

for niter in range(nitermax):    
    X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

    model = LogisticRegression(penalty='none',C=5, solver='lbfgs', l1_ratio=None)
 
    X_oot = X_oot_orig.copy()
    X_trn_save = X_trn.copy()
    Y_trn_save = Y_trn.copy()

    model.fit(X_trn, Y_trn.values.ravel())   

    predictions = model.predict_proba(X_trn_save)[:,1]
    X_trn['predicted'] = predictions
    X_trn['fraud_label'] = Y_trn_save['fraud_label']
    topRows = int(round(X_trn.shape[0]*0.03))
    temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'fraud_label'])

    predictions = model.predict_proba(X_tst)[:,1]
    X_tst['predicted']=predictions
    X_tst['fraud_label'] = Y_tst['fraud_label']
    topRows = int(round(X_tst.shape[0]*0.03))
    temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'fraud_label'])

    predictions = model.predict_proba(X_oot)[:,1]
    X_oot['predicted']=predictions
    X_oot['fraud_label'] = Y_oot['fraud_label']
    topRows = int(round(X_oot.shape[0]*0.03))
    temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'fraud_label'])
    print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
    
print(FDR3.mean())
print(FDR3)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:1320: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0 0.48720694989884566 0.4997225305216426 0.47611064543168485

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:1320: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

1 0.49402771141901575 0.4872077028885832 0.47778709136630343

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:1320: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2 0.49555107367421997 0.4835103409726104 0.47778709136630343
trn    0.492262
tst    0.490147
oot    0.477228
dtype: float64
        trn       tst       oot
0  0.487207  0.499723  0.476111
1  0.494028  0.487208  0.477787
2  0.495551  0.483510  0.477787

## Models. You can comment out any of these cells and just explore one model type. You can also just rerun that single cell multiple times as you explore different model hyperparameters.

In [ ]:
DecisionTreeClassifier()
(*, criterion="gini", 
splitter="best", 
ax_depth=None, 
min_samples_split=2, 
min_samples_leaf=1, 
min_weight_fraction_leaf=0, 
max_features=None, 
random_state=None, 
max_leaf_nodes=None, 
min_impurity_decrease=0, 
min_impurity_split=None, 
class_weight=None, presort='deprecated', ccp_alpha=0) -> None

In [140]:
%%time
# Single DT

for niter in range(nitermax):    
    X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

    model = DecisionTreeClassifier(criterion="gini",max_features='auto',min_samples_leaf=60,min_samples_split=300,splitter="best"  )
 
    X_oot = X_oot_orig.copy()
    X_trn_save = X_trn.copy()
    Y_trn_save = Y_trn.copy()

    model.fit(X_trn, Y_trn.values.ravel())   

    predictions = model.predict_proba(X_trn_save)[:,1]
    X_trn['predicted'] = predictions
    X_trn['fraud_label'] = Y_trn_save['fraud_label']
    topRows = int(round(X_trn.shape[0]*0.03))
    temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'fraud_label'])

    predictions = model.predict_proba(X_tst)[:,1]
    X_tst['predicted']=predictions
    X_tst['fraud_label'] = Y_tst['fraud_label']
    topRows = int(round(X_tst.shape[0]*0.03))
    temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'fraud_label'])

    predictions = model.predict_proba(X_oot)[:,1]
    X_oot['predicted']=predictions
    X_oot['fraud_label'] = Y_oot['fraud_label']
    topRows = int(round(X_oot.shape[0]*0.03))
    temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'fraud_label'])
    print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
    
print(FDR3.mean())

0 0.5194011976047904 0.5250205086136177 0.49706621961441744
1 0.5103546774577482 0.5023578363384189 0.4861693210393965
2 0.5055753262158956 0.5088062622309197 0.4861693210393965
trn    0.511777
tst    0.512062
oot    0.489802
dtype: float64
CPU times: user 3.33 s, sys: 1.34 s, total: 4.67 s
Wall time: 5.86 s

In [ ]:
# Random Forest parameters

# RandomForestClassifier()
# n_estimators=100, *, 
# criterion="gini", 
# max_depth=None, 
# min_samples_split=2, 
# min_samples_leaf=1, 
# min_weight_fraction_leaf=0, 
# max_features="auto", 
# max_leaf_nodes=None, 
# min_impurity_decrease=0, 
# min_impurity_split=None,
#  bootstrap=True, 
#  oob_score=False, 
#  n_jobs=None, random_state=None, verbose=0, warm_start=False, class_weight=None, ccp_alpha=0, max_samples=None) -> None

In [63]:
%%time
# Random forest 

for niter in range(nitermax):    
    X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

    model = RandomForestClassifier(n_estimators=50, min_samples_leaf=2, bootstrap=False)
    X_oot = X_oot_orig.copy()
    X_trn_save = X_trn.copy()
    Y_trn_save = Y_trn.copy()

    model.fit(X_trn, Y_trn.values.ravel())   

    predictions = model.predict_proba(X_trn_save)[:,1]
    X_trn['predicted'] = predictions
    X_trn['fraud_label'] = Y_trn_save['fraud_label']
    topRows = int(round(X_trn.shape[0]*0.03))
    temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'fraud_label'])

    predictions = model.predict_proba(X_tst)[:,1]
    X_tst['predicted']=predictions
    X_tst['fraud_label'] = Y_tst['fraud_label']
    topRows = int(round(X_tst.shape[0]*0.03))
    temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'fraud_label'])

    predictions = model.predict_proba(X_oot)[:,1]
    X_oot['predicted']=predictions
    X_oot['fraud_label'] = Y_oot['fraud_label']
    topRows = int(round(X_oot.shape[0]*0.03))
    temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'fraud_label'])
    print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
    
print(FDR3.mean())

0 0.5191127890514393 0.5253469272160861 0.5008382229673093
1 0.5205219454329775 0.5227844562482528 0.5004191114836547
2 0.5236910684671878 0.5169705469845722 0.5004191114836547
trn    0.521109
tst    0.521701
oot    0.500559
dtype: float64
CPU times: user 52.4 s, sys: 3.74 s, total: 56.2 s
Wall time: 1min 1s

In [ ]:
# Boosting Tree Variables

# lgb.LGBMClassifier()
# boosting_type='gbdt', 
# num_leaves=31, 
# max_depth=- 1, 
# learning_rate=0.1, 
# n_estimators=100, 
# subsample_for_bin=200000, 
# objective=None, 
# class_weight=None, 
# min_split_gain=0.0, 
# min_child_weight=0.001, 
# min_child_samples=20, 
# subsample=1.0, 
# subsample_freq=0, 
# colsample_bytree=1.0, 
# reg_alpha=0.0, 
# reg_lambda=0.0, 
# random_state=None, 
# n_jobs=- 1, 
# importance_type='split', **kwargs)[source]

In [59]:
%%time
# Boosting Tree

for niter in range(nitermax):    
    X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

    model = lgb.LGBMClassifier(max_depth= 4,num_leaves=15, learning_rate=0.1, n_estimators=200)

    X_oot = X_oot_orig.copy()
    X_trn_save = X_trn.copy()
    Y_trn_save = Y_trn.copy()

    model.fit(X_trn, Y_trn.values.ravel())   

    predictions = model.predict_proba(X_trn_save)[:,1]
    X_trn['predicted'] = predictions
    X_trn['fraud_label'] = Y_trn_save['fraud_label']
    topRows = int(round(X_trn.shape[0]*0.03))
    temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'fraud_label'])

    predictions = model.predict_proba(X_tst)[:,1]
    X_tst['predicted']=predictions
    X_tst['fraud_label'] = Y_tst['fraud_label']
    topRows = int(round(X_tst.shape[0]*0.03))
    temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'fraud_label'])

    predictions = model.predict_proba(X_oot)[:,1]
    X_oot['predicted']=predictions
    X_oot['fraud_label'] = Y_oot['fraud_label']
    topRows = int(round(X_oot.shape[0]*0.03))
    temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'fraud_label'])
    print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
    
print(FDR3.mean())

0 0.5204825032843664 0.523390203632361 0.49832355406538137
1 0.5227786368502438 0.5180555555555556 0.49874266554903607
2 0.524186772296243 0.514961915125136 0.5008382229673093
trn    0.522483
tst    0.518803
oot    0.499301
dtype: float64
CPU times: user 1min 7s, sys: 3.72 s, total: 1min 11s
Wall time: 33.2 s

In [ ]:
MLPClassifier()
MLPClassifier(hidden_layer_sizes=(100, ), activation="relu", *, solver='adam', 
alpha=0.0001, batch_size='auto', learning_rate="constant", learning_rate_init=0.001, 
power_t=0.5, max_iter=200, shuffle=True, random_state=None, tol=0.0001, verbose=False, 
warm_start=False, momentum=0.9, nesterovs_momentum=True, 
early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, 
epsilon=1e-8, n_iter_no_change=10, max_fun=15000)

In [49]:
%%time
# NN

for niter in range(nitermax):    
    X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

    model = MLPClassifier(alpha=0.01,activation="relu",learning_rate='adaptive', learning_rate_init=0.005,max_iter=300)

    X_oot = X_oot_orig.copy()
    X_trn_save = X_trn.copy()
    Y_trn_save = Y_trn.copy()

    model.fit(X_trn, Y_trn.values.ravel())   

    predictions = model.predict_proba(X_trn_save)[:,1]
    X_trn['predicted'] = predictions
    X_trn['fraud_label'] = Y_trn_save['fraud_label']
    topRows = int(round(X_trn.shape[0]*0.03))
    temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'fraud_label'])

    predictions = model.predict_proba(X_tst)[:,1]
    X_tst['predicted']=predictions
    X_tst['fraud_label'] = Y_tst['fraud_label']
    topRows = int(round(X_tst.shape[0]*0.03))
    temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'fraud_label'])

    predictions = model.predict_proba(X_oot)[:,1]
    X_oot['predicted']=predictions
    X_oot['fraud_label'] = Y_oot['fraud_label']
    topRows = int(round(X_oot.shape[0]*0.03))
    temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'fraud_label'])
    print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
    
print(FDR3.mean())

0 0.5210965435041717 0.5153442079071053 0.501257334450964
1 0.522142605426994 0.5120206067544362 0.4979044425817267
2 0.5220711047482701 0.5175172413793103 0.501257334450964
trn    0.521770
tst    0.514961
oot    0.500140
dtype: float64
CPU times: user 17min 47s, sys: 23.5 s, total: 18min 10s
Wall time: 10min 7s

In [19]:
print('duration: ', datetime.now() - start_time)

duration:  0:03:48.900114